blank_issues_enabled: true
templates:
  - name: Issue Feature Proposal
    about: Please propose new features here.
    title: "[Feature Proposal] "
    body: |
      <!--
      Thank you for submitting a feature proposal!
      Please provide a detailed description of your proposed feature.
      -->
    url: .github/ISSUE_TEMPLATE/issue_template-feature-proposal.yml

  - name: Issue Bug Report
    about: Please report security vulnerabilities here.
    title: "[Bug Report] "
    body: |
      <!--
      Thank you for submitting a bug report!
      Please provide a clear and concise description of the issue.
      -->https://github.com/Mel-iza/Github-Templates/blob/main
    url: .github/ISSUE_TEMPLATE/issue_template-bug-report.yml 

