name: testing and automatic pull request template via github actions

on:
  push:
    paths:
      - 'teste.yaml'

jobs: 
  updateAuthors:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Read YAML file
        id: read_yaml
        run: |
          type=$(grep 'type:' teste.yaml | awk '{print $2}')
          delete_branch=$(grep 'delete_branch_after_push:' teste.yaml | awk '{print $2}')
          echo "::set-output name=type::$type"
          echo "::set-output name=delete_branch::$delete_branch"
    
      - name: Render template
        id: template
        uses: chuhlomin/render-template@v1.4
        with:
          template: | 
            if [ "${type}" == 'training' ]; then
                template='.github/build.md'
            elif [ "${type}" == 'code_update' ]; then
                template='.github/review.md' 
            else
                template='.github/test-pull_request_template.md'
            fi      
          vars: | 
            user_commit: "${{ github.actor }}"
            label: "${{ steps.read_yaml.outputs.type }}"

      - name: Extract commit data
        id: commit_data      
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Assingees and reviewers
        id: assingees_reviewers
        uses: kentaro-m/auto-assign-action@v2.0.0
      
      - name: Create Pull Request
        id: creating_pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}
          title: '[${{ steps.read_yaml.outputs.type }}]: ${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}'
          committer: ${{ env.GIT_COMMIT_COMMITTER }}
          author: ${{ env.GIT_COMMIT_AUTHOR }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          label: | 
            ${{ steps.read_yaml.outputs.type }}
            automated_pull_request
          reviewers: ''
          assignees: ${{ env.GIT_COMMIT_AUTHOR }}
          delete-branch: ${{ steps.read_yaml.outputs.delete_branch }}
          body: |
            $(date +%d-%m-%Y) | This is an auto-generated PR with a template.
            ${{ steps.template.outputs.result }}
            User who committed: ${{ steps.template.outputs.user_commit }}
            User who can review: ${{ steps.template.outputs.user_reviewer }}
            Label: ${{ steps.template.outputs.label }}
          body-path: ${{ steps.template.outputs.result }}
          branch: pr-branch
